apiVersion: v1
kind: Service
metadata:
  name: executor-service
  labels:
    app: executor-service
    component: code-execution
spec:
  type: ClusterIP
  selector:
    app: executor-service
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
  sessionAffinity: None
